package bourse;


/**
* bourse/Bourse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bourse.idl
* Tuesday, February 5, 2019 4:23:11 PM CET
*/

public interface Bourse extends BourseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bourse
